export const ADD_NEW_APPLICATION = 'ADD_NEW_APPLICATION';
// export const ADD_NEW_APPLICATION_SUCCESS = 'ADD_NEW_APPLICATION_SUCCESS';
// export const ADD_NEW_APPLICATION_FAILED = 'ADD_NEW_APPLICATION_FAILED';
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';

